package com.enlern.new_wsn.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.enlern.new_wsn.greendao.WsnNodeBean;

import com.enlern.new_wsn.greendao.WsnNodeBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig wsnNodeBeanDaoConfig;

    private final WsnNodeBeanDao wsnNodeBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        wsnNodeBeanDaoConfig = daoConfigMap.get(WsnNodeBeanDao.class).clone();
        wsnNodeBeanDaoConfig.initIdentityScope(type);

        wsnNodeBeanDao = new WsnNodeBeanDao(wsnNodeBeanDaoConfig, this);

        registerDao(WsnNodeBean.class, wsnNodeBeanDao);
    }
    
    public void clear() {
        wsnNodeBeanDaoConfig.clearIdentityScope();
    }

    public WsnNodeBeanDao getWsnNodeBeanDao() {
        return wsnNodeBeanDao;
    }

}
